general:
    # Can be one of: debug, info, warning, error, critical
    log_level: debug

# Where the GPIO daemon runs
gpio:
    host: 192.168.178.27
    port: 8888

# Information about your LED strip and how it is connected to your RBP
led_strip:
    spi_channel: 0
    spi_frequency: 1000000
    total_led_count: 160
    usable_led_count: 90

# Settings that can be made for specific animations
animations:
    general:
        target_frame_rate: 24

    color_wheel:
        loop_mode: ENDLESS
        duration: 10.0
        scale_factor: 1.0
        target_frame_rate: 24.0

    fade:
        duration: 1.0
